config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'blogs#index'

  resources :blogs
  resources :users, only: [:show]
  # get 'blogs' => 'blogs#index'
  # get 'blogs/new' => 'blogs#new'
  # post 'blogs' => 'blogs#create'
  # delete 'blogs/:id' => 'blogs#destroy'
  # patch   'blogs/:id'  => 'blogs#update'
  # get   'blogs/:id/edit'  => 'blogs#edit'
  # get 'users/:id' => 'users#show'
  # get 'blogs/id' => 'blogs#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bblog.rb
class Bblog < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bblogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end


end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :move_to_index, except: :index


  def index
    @blog = Bblog.includes(:user).page(params[:page]).per(5).order("created_at DESC")
  end

  def new
  end

  def create
    Bblog.create(name: blog_params[:name], text: blog_params[:text], user_id: current_user.id)
    redirect_to "/blogs"
  end

  def destroy
    blog = Bblog.find(params[:id])
    blog.destroy if blog.user_id == current_user.id
  end

    def edit
      @blog = Bblog.find(params[:id])
    end

    def update
      @blog = Bblog.find(params[:id])
      if @blog.user_id == current_user.id
        @blog.update(blog_params)
      end

    end

# 詳細ページに表示したい情報をshowアクションに定義
    def show
      @blog = Bblog.find(params[:id])
    end


  private
  def blog_params
    params.permit(:name, :text)
    params.require(:bblog).permit(:name, :text)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @name = current_user.name
    @blog = current_user.bblogs.page(params[:page]).per(5).order("created_at DESC")
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_blog.html.erb
    <div class="card">
      <div class="card-content">
        <p><%= simple_format(blog.text) %></p>
        <br><br>
        <% if user_signed_in? && current_user.id == blog.user_id %>

        <a class="waves-effect waves-light btn" <%= link_to '編集', "/blogs/#{blog.id}/edit", method: :get %></a>
        <a class="waves-effect waves-light btn" <%= link_to '削除', "/blogs/#{blog.id}", method: :delete %></a>
        <% end %>
      </div>
      <div class="card-action">
        <span class="name">NAME : <%= blog.name %></span>
      </div>
      </div>

app/views/blogs/create.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      投稿が完了しました。
    </h3>
    <a class="btn" href="/blogs">投稿一覧へ戻る</a>
  </div>
</div>

app/views/blogs/destroy.html.erb
<div class="contents row">
  <div class="success">
    <h4>
      削除が完了しました。
    </h4>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true, url: blog_path) do |form| %>
    <h4>
      編集する
    </h4>
    TEXT<%= form.text_field :text %>
  <%= form.submit %>
<% end %>

app/views/blogs/index.html.erb
<div class="row">
<% @blog.each do |blog| %>
  <div class="col s12 m7 blogpost">


<%= render partial: "blog", locals: { blog: blog } %>

    </div>
  <% end %>
</div>
  <%= paginate(@blog) %>

app/views/blogs/new.html.erb
 <div class="contents row">

<%= form_with url: blogs_path do |form| %>
    <h4>
      投稿する
    </h4>
  NAME<%= form.text_field :name %>
  TEXT<%= form.text_field :text %>
  <%= submit_tag %>
<% end %>


</div>

app/views/blogs/show.html.erb
<div class ="contents row">

    <% if user_signed_in? && current_user.id == @blog.user_id %>
     <li> <%= link_to '詳細', "/blogs/#{blog.id}", method: :get %></li>
    <% end %>

    <%= simple_format(@blog.text) %>

    <span class="name">
      <a href="/users/<%= @blog.user.id %>">
        <span>投稿者</span><%= @blog.user.name %>
      </a>
    </span>
  </div>
</div>

app/views/blogs/update.html.erb
<div class="contents row">
  <div class="success">
    <h3>
      更新が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
<!-- 絶対消さない_ここから -->
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<!-- 絶対消さない_ここまで -->

<!-- テンプレの読み込み -->
 <script
    src="https://code.jquery.com/jquery-3.3.1.js"
    integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
    crossorigin="anonymous"></script>

 <!--  -- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
<!-- テンプレ読み込みここまで -->

<!-- <link href="/app/assets/stylesheets/style.css" rel="stylesheet" type="text/css"> -->

</head>

<body>
  <header>
        <nav class ="#212121 grey darken-4">
          <div class="nav-wrapper">
            <a href="/" class="brand-logo">Blog</a>

            <ul id="nav-mobile" class="right hide-on-med-and-down">
              <% if user_signed_in? %>
              <li><a href="/users/<%= current_user.id %>">マイページ</a></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
              <li><a class="post" href="/blogs/new">投稿する</a></li>

           <% else %>
              <li><%= link_to "ログイン", new_user_session_path, class: 'post' %></li>
              <li><%= link_to "新規登録", new_user_registration_path, class: 'post' %></li>
            </ul>
            <% end %>
          </div>
        </nav>

  </header>

    <%= yield %>

    <footer>
    </footer>

  </body>
</html>

app/views/users/show.html.erb
<div class="row">
  <h4><%= @name %>さんの投稿一覧</h4>
  <% @blog.each do |blog| %>

<div class="col s12 m7 blogpost">

<%= render partial: "blogs/blog", locals: { blog: blog } %>

</div>
  <% end %>

</div>

  <%= paginate(@blog) %>